//!******************************************************************************************
//!
//!   raylib-zig port of the [textures] example - Load textures from raw data
//!   https://github.com/raysan5/raylib/blob/master/examples/textures/textures_raw_data.c
//!
//!   Example complexity rating: [★★★☆] 3/4
//!
//!   NOTE: Images are loaded in CPU memory (RAM); textures are loaded in GPU memory (VRAM)
//!
//!   Example originally created with raylib 1.3, last time updated with raylib 3.5
//!
//!   Translated to raylib-zig by Timothy Fiss (@TheFissk)
//!
//!   Example licensed under an unmodified zlib/libpng license, which is an OSI-certified,
//!   BSD-like license that allows static linking with closed source software
//!
//!   Copyright (c) 2015-2025 Ramon Santamaria (@raysan5)
//!
//!*******************************************************************************************

const rl = @import("raylib");
const std = @import("std");

//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
pub fn main() anyerror!void {
    // Initialization
    //--------------------------------------------------------------------------------------
    const screenWidth = 800;
    const screenHeight = 450;

    rl.initWindow(screenWidth, screenHeight, "raylib [textures] example - texture from raw data");

    // NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)

    // Load RAW image data (512x512, 32bit RGBA, no file header)
    const fudesumiRaw = try rl.loadImageRaw("examples/textures/resources/fudesumi.raw", 384, 512, .uncompressed_r8g8b8a8, 0);
    const fudesumi = try rl.loadTextureFromImage(fudesumiRaw); // Upload CPU (RAM) image to GPU (VRAM)
    fudesumiRaw.unload(); // Unload CPU (RAM) image data

    // Generate a checked texture by code
    const width = 960;
    const height = 480;

    // note the use of the raw c allocator here, since we will be passing this pointer to raylib
    // and raylib expects to be able to free() it when we unload the image.
    // Other allocators may use different memory management strategies that are incompatible with this.
    const c_alloc = std.heap.c_allocator;
    var pixels = try c_alloc.alloc(rl.Color, width * height);

    for (0..height) |y| {
        for (0..width) |x| {
            if ((@divFloor(x, 32) + @divFloor(y, 32)) % 2 == 0) {
                pixels[y * width + x] = .orange;
            } else {
                pixels[y * width + x] = .gold;
            }
        }
    }

    // Load pixels data into an image structure and create texture
    const checkedIm = rl.Image{
        .data = pixels.ptr, // We can assign pixels directly to data
        .width = width,
        .height = height,
        .format = .uncompressed_r8g8b8a8,
        .mipmaps = 1,
    };

    const checked = try rl.loadTextureFromImage(checkedIm);
    defer checked.unload();
    checkedIm.unload();

    rl.setTargetFPS(60); // Set our game to run at 60 frames-per-second
    //---------------------------------------------------------------------------------------

    // Main game loop
    while (!rl.windowShouldClose()) // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        // TODO: Update your variables here
        //----------------------------------------------------------------------------------

        // Draw
        //----------------------------------------------------------------------------------
        rl.beginDrawing();
        defer rl.endDrawing();

        rl.clearBackground(.ray_white);

        rl.drawTexture(
            checked,
            screenWidth / 2 - @divFloor(checked.width, 2),
            screenHeight / 2 - @divFloor(checked.height, 2),
            rl.fade(.white, 0.5),
        );
        rl.drawTexture(fudesumi, 430, -30, .white);

        rl.drawText("CHECKED TEXTURE ", 84, 85, 30, .brown);
        rl.drawText("GENERATED by CODE", 72, 148, 30, .brown);
        rl.drawText("and RAW IMAGE LOADING", 46, 210, 30, .brown);

        rl.drawText("(c) Fudesumi sprite by Eiden Marsal", 310, screenHeight - 20, 10, .brown);

        //----------------------------------------------------------------------------------
    }
}
