name: Check examples emscripten

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  check-examples:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up ubuntu packages
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.17.0-dev.305+bdfbf432d

      - name: Verify examples can build for emscripten
        run: zig build -Dtarget=wasm32-emscripten -Doptimize=ReleaseSmall examples