name: Check examples

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  check-examples:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up ubuntu packages
        if: startsWith(matrix.os, 'ubuntu')
        run:
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            libglfw3 libglfw3-dev libx11-dev libxcursor-dev \ 
            libxrandr-dev libxinerama-dev libxi-dev libxext-dev \
            libxfixes-dev libwayland-dev libxkbcommon-dev

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Verify generated files are up to date
        run: zig build examples